# The Travis setup:
# - run testsuite for every PHP version
# - run lint for every PHP version
# - run Selenium for single PHP version

language: php

php:
  - "7.0"
  - "5.6"
  - "5.5"
  - hhvm

sudo: false

env:
  matrix:
    - CI_MODE=test
    - CI_MODE=lint
  global:
    - TESTSUITE_USER=root
    - TESTSUITE_PASSWORD=root
    - TESTSUITE_URL=http://127.0.0.1:8000

install:
  - ./test/ci-install-$CI_MODE
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ] ; then phpenv config-add test/php-noprofile.ini ; fi

before_script:
  - export PATH=~/.composer/vendor/bin/:$PATH
  - mysql -uroot -e "CREATE DATABASE test"
  - mysql -uroot < sql/create_tables.sql
  - mysql -uroot -e "SET PASSWORD = PASSWORD('$TESTSUITE_PASSWORD')"
  - ./test/start-local-server

script:
  - ant clean
  - ./test/ci-$CI_MODE

after_script:
  - if [ -f vendor/bin/coveralls ] ; then php vendor/bin/coveralls -v || true ; fi
  - if [ -f vendor/bin/codacycoverage ] ; then php vendor/bin/codacycoverage clover || true ; fi
  - if [ -f ~/.local/bin/codecov ] ; then ~/.local/bin/codecov ; fi
  - if [ -f php.log ] ; then cat php.log ; fi

matrix:
  allow_failures:
    - php: "7.0"
      env: CI_MODE=selenium
  fast_finish: true
  include:
    - php: "7.0"
      env: CI_MODE=selenium
    - php: "7.0"
      env: CI_MODE=release
cache:
  directories:
    - $HOME/.composer/cache/
    - $HOME/browserstack
    - $HOME/runkit
    - $HOME/.cache/pip
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
addons:
  apt:
    packages:
    - git
    - python-coverage
    sources:
    - git-core
